DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS businesses;

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE businesses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  favored TEXT NOT NULL
  FOREIGN KEY (author_id) REFERENCES user (id)
);